#######################
# DKT, for CIFAR100 #
#######################

# Model definition
model: RVT
embed_dim: [32]
depth: [5]
num_heads: [12]
patch_size: 4
input_size: 32

# Training setting
no_amp: true
eval_every: 50

# Base hyperparameter
weight_decay: 0.000001
batch_size: 256
incremental_batch_size: 256
incremental_lr: 0.0005
rehearsal: icarl_all

# Knowledge Distillation
auto_kd: true

# Finetuning
finetuning: balanced
ft_no_sampling: true

# DKT model
DKT: true
freeze_task: [old_task_tokens, old_heads]
freeze_ft: [sab, task_tokens]

# Independent Classifiers
ind_clf: 1-1
bce_loss: true


## Erasing
reprob: 0.0
remode: pixel
recount: 1
resplit: false
